### PR TITLE
Epic/701 updates

### PR DESCRIPTION
**Pull request by duane701**
Combine our changes with the original repository.

### CODE REVIEW

**Comment by duane701** [comment]
@Khoa-Tran701 Take a look. I fixed the `ControlMode `the same way that was done in Vidar.

**Comment by toxicoreos** [comment]
LGTM

**Review by toxicoreos — APPROVED** [review]
LGTM

**Comment by toxicoreos** [comment]
I've noticed no notable changes when using Vidar's method of control mode and the original method of control mode.  Both seem to not work as intended so far.

**Comment by duane701** [comment]
> no notable changes when using Vidar's method of control mode and the original method of control mode

That's correct. The change is intended to improve readability not change the operation.

**Pull request merged**
